version: "3"

services:
  
  mongodb1:
    image: mongo:latest
    container_name: mongodev1
    networks:
      - mongonetwork
    ports:
      - 30001:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongodb2:
    image: mongo:latest
    container_name: mongodev2
    volumes: 
      - ./db-backup/primary:/data/db
    networks:
      - mongonetwork
    ports:
      - 30002:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo-startup:
    image: mongo
    container_name: startup-agent-dev
    networks:
      - mongonetwork
    depends_on:
      - mongodb1
      - mongodb2

    volumes:
      - ./mongo-startup:/mongo-startup
    entrypoint:
      - /mongo-startup/initiate_replica.sh

  
networks:
  mongonetwork:

